Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/jupyer-book/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/anaconda3/envs/jupyer-book/lib/python3.9/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/anaconda3/envs/jupyer-book/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/anaconda3/envs/jupyer-book/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/anaconda3/envs/jupyer-book/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/anaconda3/envs/jupyer-book/lib/python3.9/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/usr/local/anaconda3/envs/jupyer-book/lib/python3.9/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/anaconda3/envs/jupyer-book/lib/python3.9/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
suppressPackageStartupMessages({
  library(dplyr)
  library(readr)
  library(kableExtra)
  library(IRdisplay)
}) # hide annoying messages
options(knitr.kable.NA = '') # don't plot missing values
humanPopulation <- read_tsv("../data/humans.tsv", col_types = "nn") 
humanPopulation %>% 
  mutate(dN = c(diff(population), NA), dT = c(diff(year), NA), rate = 1 / population * dN / dT) %>% 
  kbl(col.names = c("t (years)", "N (billions)", "$\\Delta N$", "$\\Delta t$", "$\\frac{1}{N} \\frac{\\Delta N}{\\Delta t}$"), 
    caption = "Human population numbers for analysis,
    digits = c(0, 3, 3, 0, 4)) %>%
  as.character() %>%
  display_html()
------------------

Error in parse(text = x, srcfile = src): <text>:12:15: unexpected INCOMPLETE_STRING
14:   as.character() %>%
15:   display_html()
                  ^
Traceback:

ERROR: Error in parse(text = x, srcfile = src): <text>:12:15: unexpected INCOMPLETE_STRING
14:   as.character() %>%
15:   display_html()
                  ^


